"""Signal 1 — LLM classifier (Groq, llama-3.3-70b-versatile).

Asks a capable model to holistically judge whether a passage reads as
AI-generated, returning a calibrated probability plus a one-line rationale.

What it captures: semantic and stylistic coherence — the "does this *sound*
like a machine wrote it" read that structural stats can't see (evenly hedged
phrasing, generic transitions, low idiosyncrasy).

Blind spot: it is nondeterministic and can be overconfident; lightly-edited AI
or a genuinely unusual human voice can fool it. On any API/parse failure we
fall back to p_ai=0.5 ("can't tell") rather than guessing — the pipeline stays
honest instead of inventing a verdict.
"""
import json

from groq import Groq

import config

_client = None

_SYSTEM_PROMPT = """You are a forensic text-attribution assistant for a creative platform.
Judge whether the passage was written by a human or generated by an AI system.

Be well-calibrated and decisive on clear cases:
- Clear AI hallmarks (generic, content-light phrasing, even hedging, formulaic
  transitions like "It is important to note"/"Furthermore", low idiosyncrasy)
  -> report 0.8-0.95.
- Clear human idiosyncrasy (personal voice, irregular rhythm, slang, typos,
  lived detail) -> report 0.05-0.2.
- Only stay near 0.5 when the text is genuinely mixed or too short to judge.

Do NOT flag text as AI merely for being formal. Dense, domain-specific,
substantive prose (real academic/technical content, specific claims, expert
terminology) is usually HUMAN expert writing — score it 0.4-0.6, not high. AI
boilerplate is generic and content-light; formal human writing carries real
information. Falsely accusing a human writer is the costlier error, so when torn
between "uncertain" and "AI", lean toward the lower (more human) probability.

Respond with ONLY a JSON object, no prose, in exactly this shape:
{"p_ai": <float 0..1>, "rationale": "<one short sentence>"}
where p_ai is your probability the text is AI-generated (1.0 = certainly AI,
0.0 = certainly human, 0.5 = genuinely can't tell)."""


def _get_client():
    global _client
    if _client is None:
        if not config.GROQ_API_KEY:
            raise RuntimeError("GROQ_API_KEY is not set")
        _client = Groq(api_key=config.GROQ_API_KEY)
    return _client


def _fallback(reason):
    return {"p_ai": 0.5, "rationale": f"unavailable ({reason}); defaulting to uncertain", "ok": False}


def analyze(text):
    """Return {'p_ai': float, 'rationale': str, 'ok': bool}."""
    try:
        client = _get_client()
        resp = client.chat.completions.create(
            model=config.GROQ_MODEL,
            temperature=0.0,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": text},
            ],
        )
        raw = resp.choices[0].message.content
        data = json.loads(raw)
        p_ai = float(data["p_ai"])
        if not 0.0 <= p_ai <= 1.0:
            return _fallback("model returned out-of-range probability")
        return {
            "p_ai": round(p_ai, 4),
            "rationale": str(data.get("rationale", "")).strip()[:300],
            "ok": True,
        }
    except (KeyError, ValueError, TypeError, json.JSONDecodeError) as exc:
        return _fallback(f"could not parse model reply: {exc}")
    except Exception as exc:  # network / auth / rate-limit from Groq
        return _fallback(f"{type(exc).__name__}: {exc}")
